# Generated by Django 3.1.1 on 2020-11-09 21:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201109_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 21, 0, 15, 780351, tzinfo=utc)),
        ),
    ]
