# Generated by Django 3.1.1 on 2020-11-13 08:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201113_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 8, 54, 15, 936964, tzinfo=utc)),
        ),
    ]
