# Generated by Django 3.1.1 on 2020-11-13 18:00

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_auto_20201113_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 18, 0, 26, 311160, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_save',
        ),
        migrations.AddField(
            model_name='post',
            name='is_save',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
